### ISSUE TITLE
MobileNet --input_layer flag

### ISSUE THREAD

**Issue by tomrichardon** [ronny3050/MobileNet#1]
I get

> TypeError: Cannot interpret feed_dict key as Tensor: The name 'DecodeJpeg/contents:0' refers to a Tensor which does not exist. The operation, 'DecodeJpeg/contents', does not exist in the graph.

when I try to infer on a MobileNet model retrained with your code.

"DecodeJpeg/contents:0" is the name of the input operation in Inception V3, but do you know what I should pass as the --input_layer flag when infering with MobileNet ?

**Comment by ronny3050** [comment]
I believe it is 'input:0'
